# Generated by Django 4.0.4 on 2022-06-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ad_name', models.CharField(max_length=100)),
                ('ad_mobile', models.CharField(max_length=100)),
                ('ad_email', models.CharField(max_length=100)),
                ('ad_password', models.CharField(max_length=100)),
                ('ad_status', models.CharField(max_length=100)),
                ('ad_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('ap_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ap_hospital_name', models.CharField(max_length=100)),
                ('ap_user_name', models.CharField(max_length=100)),
                ('ap_request_status', models.CharField(max_length=100)),
                ('ap_status', models.CharField(max_length=100)),
                ('ap_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hs_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('hs_name', models.CharField(max_length=100)),
                ('hs_email', models.CharField(max_length=100)),
                ('hs_mobile', models.CharField(max_length=100)),
                ('hs_address', models.CharField(max_length=100)),
                ('hs_image', models.FileField(upload_to='app/static/media/image')),
                ('hs_hrn', models.CharField(max_length=100)),
                ('hs_hrc', models.FileField(upload_to='app/static/media/hrc')),
                ('hs_password', models.CharField(max_length=100)),
                ('hs_status', models.CharField(max_length=100)),
                ('hs_created_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('us_name', models.CharField(max_length=100)),
                ('us_mobile', models.CharField(max_length=100)),
                ('us_email', models.CharField(max_length=100)),
                ('us_password', models.CharField(max_length=100)),
                ('us_status', models.CharField(max_length=100)),
                ('us_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
