# Generated by Django 4.0.4 on 2022-06-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ap_user_email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ap_user_phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
