# Generated by Django 4.0.4 on 2022-06-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment_ap_user_email_appointment_ap_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('dc_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dc_name', models.CharField(max_length=100)),
                ('dc_mobile', models.CharField(max_length=100)),
                ('dc_email', models.CharField(max_length=100)),
                ('dc_password', models.CharField(max_length=100)),
                ('dc_status', models.CharField(max_length=100)),
                ('dc_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
