# Generated by Django 4.0.4 on 2022-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surrogate',
            fields=[
                ('sr_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('sr_name', models.CharField(max_length=100)),
                ('sr_mobile', models.CharField(max_length=100)),
                ('sr_email', models.CharField(max_length=100)),
                ('sr_password', models.CharField(max_length=100)),
                ('sr_aadhar', models.FileField(upload_to='app/static/media/aadhar')),
                ('sr_status', models.CharField(max_length=100)),
                ('sr_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
