# Generated by Django 4.0.4 on 2022-06-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_surrogate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ap_doctor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
