# Generated by Django 4.0.4 on 2022-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointment_ap_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='surrogate',
            name='sr_doctor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
