# Generated by Django 4.0.4 on 2022-06-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_surrogate_sr_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ap_surrogates',
            field=models.CharField(default='', max_length=100),
        ),
    ]
