# Generated by Django 4.0.4 on 2022-06-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appointment_ap_surrogates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('ch_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ch_name', models.CharField(max_length=100)),
                ('ch_hospital_name', models.CharField(max_length=100)),
                ('ch_parent_name', models.CharField(max_length=100)),
                ('ch_status', models.CharField(max_length=100)),
                ('ch_created_by', models.CharField(max_length=100)),
            ],
        ),
    ]
