# Generated by Django 4.0.4 on 2022-06-14 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('re_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('re_child_count', models.CharField(max_length=100)),
                ('re_hospital_name', models.CharField(max_length=100)),
                ('re_parent_name', models.CharField(max_length=100)),
                ('re_status', models.CharField(max_length=100)),
                ('re_created_by', models.CharField(max_length=100)),
                ('re_created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
