# Generated by Django 4.0.4 on 2022-06-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='re_amount',
            field=models.CharField(default='', max_length=100),
        ),
    ]
