# Generated by Django 4.0.4 on 2022-06-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_receipt_re_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='re_payment_status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
